<?php
/**
 * Twitter Integration Module
 *
 * @var array $strtable
 * @var array $strlegend
 * @var array $strValues
 */

$strtable['TWITTERDESCBLOC'] = 'Content';
$strtable['TWITTERDISPLAYBLOC'] = 'Display';
$strtable['SUBTITLE'] = 'Main Content';
$strlegend['SUBTITLE'] = "Summary (first reading)";
$strtable['DESCRIPTION'] = 'Detailed Content';
$strlegend['DESCRIPTION'] = "News detail";
$strtable['ACTIONBLOC'] = 'Action';
$strtable['ACTION'] = 'Action';
$strtable['TWITTERDEFBLOC'] = 'Definition';
$strtable['LABEL'] = 'Label';
$strtable['POSITION'] = 'Position';
$strValues['POSITION']['primary'] = 'Main';
$strtable['TWITTERIDLINK'] = 'Link to tweet';
